'"hola"
'(+ 3 5)
'(and #t #f)
'(or #t #f)
'(< 1 2)
'(isZero? 3)
'(++ 7)
'(-- 5)
'(equal? #t #f)
'(define x 3)
'(begin x 4 (list 1 #t #f))
'(if #t 4)
'(if #t 1 0)
'(while [(< 2 0)] (++ 2))
'(lambda ([x Int] [y Bool]) y)
'(let ([y Int 0] [z Int 2]) (+ z y))
'(letrec ([y Int 9]) (++ y))
'(list #t #f #f #t)
